CREATE TABLE IF NOT EXISTS dft.stats19_vehicle (
  collision_index text,
  vehicle_reference int,
  casualty_reference int,
  casualty_class dft.stats19_casualty_class,
  sex_of_casualty dft.stats19_sex_of_casualty,
  age_of_casualty int,
  age_band_of_casualty dft.stats19_age_band_of_casualty,
  casualty_severity dft.stats19_casualty_severity,
  pedestrian_location dft.stats19_pedestrian_location,
  pedestrian_movement dft.stats19_pedestrian_movement,
  car_passenger dft.stats19_car_passenger,
  bus_or_coach_passenger dft.stats19_bus_or_coach_passenger,
  pedestrian_road_maintenance_worker dft.stats19_pedestrian_road_maintenance_worker,
  casualty_type int,
  casualty_imd_decile dft.stats19_casualty_imd_decile,
  lsoa_of_casualty text,
  enhanced_casualty_severity dft.stats19_enhanced_casualty_severity,
  casualty_injury_based int,
  casualty_adjusted_serious float8,
  casualty_adjusted_slight float8,
  casualty_distance_banding dft.stats19_casualty_distance_banding
);
